Arrays solution added
fullstack-expert/study pull request #117
Opened 2021-12-04 22:52 UTC by mrandell777

2021-12-06 17:02 UTC, moklidia requested changes

2021-12-06 17:02 UTC, moklidia commented on test/exercise/arrays/solution.rb
> +        max_func = lambda do |collection, max|
Зачем через лямбду?

2021-12-06 17:13 UTC, mrandell777 commented
Робокоп написал что нужно использовать лямбду
--
Отправлено из Mail.ru для Android понедельник, 06 декабря 2021г., 20:02 +03:00 от Lidia  ***@***.*** :

***@***.*** requested changes on this pull request.
>----------------------------------------------------------------------
>In  test/exercise/arrays/solution.rb :
> @@ -2,11 +2,28 @@ module Exercise
>   module Arrays
>     class << self
>       def replace(array)
>-        array
>+        max_func = lambda do |collection, max|
>
>Зачем через лямбду?
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>Triage notifications on the go with GitHub Mobile for  iOS or  Android .

2021-12-12 13:15 UTC, mrandell777 commented on test/exercise/arrays/solution.rb
> +        max_func = lambda do |collection, max|
Изначально делал через обычную функцию, но рубокоп пишет что нужно использовать лямбду

2021-12-12 13:40 UTC, mrandell777 commented on test/exercise/arrays/solution.rb
> +        max_func = lambda do |collection, max|
Теперь сделал через цикл for. Мне изменение запушить и создать новый пулреквест или как?

2021-12-18 08:24 UTC, closed without merging